-- MySQL Script generated by MySQL Workbench
-- dom 14 dic 2025 00:18:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BO_System
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BO_System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BO_System` DEFAULT CHARACTER SET utf8 ;
USE `BO_System` ;

-- -----------------------------------------------------
-- Table `BO_System`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`persona` (
  `persona_id` CHAR(36) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `documento` VARCHAR(30) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `creado_en` DATE NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`persona_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cuit` VARCHAR(45) NOT NULL,
  `entidad` INT NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`celula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`celula` (
  `id_celula` INT NOT NULL,
  `empresa` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'default',
  `tipo_cuanta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_celula`),
  INDEX `fk_celula_empresa1_idx` (`empresa` ASC) VISIBLE,
  CONSTRAINT `fk_celula_empresa1`
    FOREIGN KEY (`empresa`)
    REFERENCES `BO_System`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`usuario` (
  `legajo` VARCHAR(5) CHARACTER SET 'binary' NOT NULL,
  `exa` VARCHAR(8) NOT NULL,
  `password_hash` VARCHAR(70) NOT NULL,
  `persona_id` CHAR(36) NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'ACTIVO',
  `celula` INT NOT NULL,
  `rol` ENUM('VENDEDOR', 'SUPERVISOR', 'BACK_OFFICE') NOT NULL,
  PRIMARY KEY (`persona_id`),
  INDEX `fk_usuario_persona1_idx` (`persona_id` ASC) VISIBLE,
  INDEX `celula_idx` (`celula` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `BO_System`.`persona` (`persona_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `celula`
    FOREIGN KEY (`celula`)
    REFERENCES `BO_System`.`celula` (`id_celula`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`vendedor` (
  `usuario_id` CHAR(36) NOT NULL,
  `vendedor` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`vendedor`),
  INDEX `fk_vendedor_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `vendedor_UNIQUE` (`vendedor` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendedor_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `BO_System`.`usuario` (`persona_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`supervisor` (
  `usuario_id` CHAR(36) NOT NULL,
  `supervisor` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_supervisor_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  PRIMARY KEY (`supervisor`),
  UNIQUE INDEX `supervisor_UNIQUE` (`supervisor` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_supervisor_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `BO_System`.`usuario` (`persona_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`back_office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`back_office` (
  `usuario` CHAR(36) NOT NULL,
  `back_office` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`back_office`),
  INDEX `fk_back_office_usuario1_idx` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `back_office_UNIQUE` (`back_office` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_back_office_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `BO_System`.`usuario` (`persona_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`cliente` (
  `persona_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`persona_id`),
  INDEX `fk_usuario_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona10`
    FOREIGN KEY (`persona_id`)
    REFERENCES `BO_System`.`persona` (`persona_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`permisos` (
  `permisos_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`permisos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`correo` (
  `spa` VARCHAR(12) NOT NULL,
  `telefono_contacto` VARCHAR(20) NOT NULL,
  `telefono_alternativo` VARCHAR(20) NULL,
  `destinatario` VARCHAR(45) NOT NULL,
  `persona_autorizada` VARCHAR(45) NULL,
  `direccion` VARCHAR(75) NOT NULL,
  `numero_casa` INT NOT NULL,
  `entre_calles` VARCHAR(85) NULL,
  `barrio` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_limite` DATE NOT NULL,
  PRIMARY KEY (`spa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`plan` (
  `plan_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `gigabyte` DECIMAL(4,1) UNSIGNED NOT NULL,
  `llamadas` VARCHAR(45) NOT NULL,
  `mensajes` VARCHAR(45) NOT NULL,
  `whatsapp` VARCHAR(45) NOT NULL,
  `roaming` VARCHAR(70) NOT NULL,
  `beneficios` VARCHAR(250) NULL,
  `precio` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `empresa_destinada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`plan_id`),
  UNIQUE INDEX `plan_id_UNIQUE` (`plan_id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`promocion` (
  `promocion_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `descuento` VARCHAR(45) NULL,
  `beneficios` VARCHAR(45) NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `empresa_destinada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`promocion_id`),
  UNIQUE INDEX `promocion_id_UNIQUE` (`promocion_id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`venta` (
  `venta_id` INT NOT NULL AUTO_INCREMENT,
  `sds` VARCHAR(16) NOT NULL,
  `chip` ENUM('SIM', 'ESIM') NOT NULL DEFAULT 'SIM',
  `stl` VARCHAR(16) NULL,
  `tipo_venta` ENUM('PORTABILIDAD', 'LINEA_NUEVA') NOT NULL,
  `sap` VARCHAR(12) NULL,
  `cliente_id` CHAR(36) NOT NULL,
  `vendedor_id` CHAR(36) NOT NULL,
  `multiple` INT NOT NULL DEFAULT 0,
  `plan_id` INT NOT NULL,
  `promocion_id` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  PRIMARY KEY (`venta_id`),
  UNIQUE INDEX `venta_id_UNIQUE` (`venta_id` ASC) VISIBLE,
  INDEX `cliente_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `vendedor_idx` (`vendedor_id` ASC) VISIBLE,
  INDEX `fk_venta_plan1_idx` (`plan_id` ASC) VISIBLE,
  INDEX `fk_venta_promocion1_idx` (`promocion_id` ASC) VISIBLE,
  INDEX `correo_idx` (`sap` ASC) VISIBLE,
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `BO_System`.`cliente` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `vendedor`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `BO_System`.`vendedor` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_venta_plan1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `BO_System`.`plan` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_venta_promocion1`
    FOREIGN KEY (`promocion_id`)
    REFERENCES `BO_System`.`promocion` (`promocion_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `correo`
    FOREIGN KEY (`sap`)
    REFERENCES `BO_System`.`correo` (`spa`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`portabilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`portabilidad` (
  `venta_id` INT NOT NULL,
  `spn` VARCHAR(12) NOT NULL,
  `empresa_origen` VARCHAR(20) NOT NULL,
  `mercado_origen` ENUM('PREPAGO', 'POSPAGO') NOT NULL,
  `numero_portar` VARCHAR(20) NOT NULL,
  `pin` VARCHAR(4) NOT NULL,
  `fecha_portacion` DATETIME NOT NULL,
  PRIMARY KEY (`venta_id`),
  CONSTRAINT `fk_portabilidad_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `BO_System`.`venta` (`venta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`linea_nueva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`linea_nueva` (
  `venta_id` INT NOT NULL,
  PRIMARY KEY (`venta_id`),
  CONSTRAINT `fk_linea_nueva_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `BO_System`.`venta` (`venta_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`estado` (
  `estado_id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(75) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `usuario_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`estado_id`),
  INDEX `fk_estado_venta1_idx` (`venta_id` ASC) VISIBLE,
  INDEX `usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_estado_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `BO_System`.`venta` (`venta_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `BO_System`.`usuario` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`permisos_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`permisos_has_usuario` (
  `permisos_id` INT NOT NULL,
  `persona_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`permisos_id`, `persona_id`),
  INDEX `fk_permisos_has_usuario_usuario1_idx` (`persona_id` ASC) VISIBLE,
  INDEX `fk_permisos_has_usuario_permisos1_idx` (`permisos_id` ASC) VISIBLE,
  CONSTRAINT `fk_permisos_has_usuario_permisos1`
    FOREIGN KEY (`permisos_id`)
    REFERENCES `BO_System`.`permisos` (`permisos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permisos_has_usuario_usuario1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `BO_System`.`usuario` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`alerta` (
  `alerta_id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `tipo_alerta` ENUM('DATOS_INCORRECTOS', 'PORTABILIDAD_RECHAZADA', 'PLAN_INCORRECTO', 'DOCUMENTACION', 'OTRO') NOT NULL,
  `comentario` VARCHAR(250) NOT NULL,
  `origen` ENUM('AUTOMATICA', 'BACK_OFFICE', 'SUPERVISOR') NOT NULL DEFAULT 'AUTOMATICA',
  `estado` ENUM('ABIERTA', 'EN_REVISION', 'RESUELTA', 'DESCARTADA') NOT NULL,
  `creada_por` CHAR(36) NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_resolucion` DATETIME NULL,
  PRIMARY KEY (`alerta_id`),
  INDEX `fk_alerta_venta1_idx` (`venta_id` ASC) VISIBLE,
  INDEX `usuario_idx` (`creada_por` ASC) VISIBLE,
  CONSTRAINT `fk_alerta_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `BO_System`.`venta` (`venta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario`
    FOREIGN KEY (`creada_por`)
    REFERENCES `BO_System`.`usuario` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`estado_correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`estado_correo` (
  `estado_correo_id` INT NOT NULL AUTO_INCREMENT,
  `correo_spa` VARCHAR(12) NOT NULL,
  `entregado_ok` TINYINT NOT NULL DEFAULT 0,
  `estado_guia` VARCHAR(45) NOT NULL DEFAULT 'INICIAL',
  `ultimo_evento_fecha` DATETIME NOT NULL,
  `ubicacion_actual` VARCHAR(75) NOT NULL DEFAULT 'PENDIENTE',
  `primera_visita` VARCHAR(45) NULL,
  `fecha_primer_visita` DATETIME NULL,
  PRIMARY KEY (`estado_correo_id`),
  INDEX `fk_estado_correo_correo1_idx` (`correo_spa` ASC) VISIBLE,
  CONSTRAINT `fk_estado_correo_correo1`
    FOREIGN KEY (`correo_spa`)
    REFERENCES `BO_System`.`correo` (`spa`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`reclamo_correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`reclamo_correo` (
  `reclamo_correo_id` INT NOT NULL,
  `correo_spa` VARCHAR(12) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(700) NOT NULL,
  PRIMARY KEY (`reclamo_correo_id`),
  INDEX `fk_reclamo_correo_correo1_idx` (`correo_spa` ASC) VISIBLE,
  CONSTRAINT `fk_reclamo_correo_correo1`
    FOREIGN KEY (`correo_spa`)
    REFERENCES `BO_System`.`correo` (`spa`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
