-- MySQL Script generated by MySQL Workbench
-- sáb 13 dic 2025 15:22:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BO_System
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BO_System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BO_System` DEFAULT CHARACTER SET utf8 ;
USE `BO_System` ;

-- -----------------------------------------------------
-- Table `BO_System`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`persona` (
  `persona` CHAR(36) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `documento` VARCHAR(30) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `creado_en` DATE NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`permisos` (
  `permisos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`permisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cuit` VARCHAR(45) NOT NULL,
  `entidad` INT NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`celula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`celula` (
  `id_celula` INT NOT NULL,
  `empresa` INT NOT NULL,
  PRIMARY KEY (`id_celula`),
  INDEX `fk_celula_empresa1_idx` (`empresa` ASC) VISIBLE,
  CONSTRAINT `fk_celula_empresa1`
    FOREIGN KEY (`empresa`)
    REFERENCES `BO_System`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`usuario` (
  `legajo` VARCHAR(5) CHARACTER SET 'binary' NOT NULL,
  `exa` VARCHAR(8) NOT NULL,
  `password_hash` VARCHAR(70) NOT NULL,
  `persona` CHAR(36) NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'ACTIVO',
  `permisos` INT NOT NULL,
  `celula` INT NOT NULL,
  `rol` ENUM('VENDEDOR', 'SUPERVISOR', 'BACK_OFFICE') NOT NULL,
  PRIMARY KEY (`persona`),
  INDEX `fk_usuario_persona1_idx` (`persona` ASC) VISIBLE,
  INDEX `fk_usuario_permisos1_idx` (`permisos` ASC) VISIBLE,
  INDEX `celula_idx` (`celula` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona`)
    REFERENCES `BO_System`.`persona` (`persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_permisos1`
    FOREIGN KEY (`permisos`)
    REFERENCES `BO_System`.`permisos` (`permisos`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `celula`
    FOREIGN KEY (`celula`)
    REFERENCES `BO_System`.`celula` (`id_celula`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`vendedor` (
  `usuario` CHAR(36) NOT NULL,
  `vendedor` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`vendedor`),
  INDEX `fk_vendedor_usuario1_idx` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `vendedor_UNIQUE` (`vendedor` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_vendedor_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `BO_System`.`usuario` (`persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`supervisor` (
  `usuario` CHAR(36) NOT NULL,
  `supervisor` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_supervisor_usuario1_idx` (`usuario` ASC) VISIBLE,
  PRIMARY KEY (`supervisor`),
  UNIQUE INDEX `supervisor_UNIQUE` (`supervisor` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_supervisor_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `BO_System`.`usuario` (`persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`back_office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`back_office` (
  `usuario` CHAR(36) NOT NULL,
  `back_office` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`back_office`),
  INDEX `fk_back_office_usuario1_idx` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `back_office_UNIQUE` (`back_office` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_back_office_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `BO_System`.`usuario` (`persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`cliente` (
  `persona` CHAR(36) NOT NULL,
  PRIMARY KEY (`persona`),
  INDEX `fk_usuario_persona1_idx` (`persona` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona10`
    FOREIGN KEY (`persona`)
    REFERENCES `BO_System`.`persona` (`persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
