-- MySQL Script generated by MySQL Workbench
-- mié 10 dic 2025 12:40:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BO_System
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BO_System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BO_System` DEFAULT CHARACTER SET utf8 ;
USE `BO_System` ;

-- -----------------------------------------------------
-- Table `BO_System`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`persona` (
  `id_persona` CHAR(36) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `documento` VARCHAR(30) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `creado_en` DATE NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cuit` VARCHAR(45) NOT NULL,
  `entidad` INT NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`usuario` (
  `legajo` VARCHAR(5) CHARACTER SET 'binary' NOT NULL,
  `rol` VARCHAR(25) NOT NULL,
  `exa` VARCHAR(8) NOT NULL,
  `password_hash` VARCHAR(70) NOT NULL,
  `persona_id` CHAR(36) NOT NULL,
  `empresa_id_empresa` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`persona_id`),
  INDEX `fk_usuario_persona1_idx` (`persona_id` ASC) VISIBLE,
  INDEX `fk_usuario_empresa1_idx` (`empresa_id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `BO_System`.`persona` (`id_persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_empresa1`
    FOREIGN KEY (`empresa_id_empresa`)
    REFERENCES `BO_System`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`supervisor` (
  `usuario` CHAR(36) NOT NULL,
  PRIMARY KEY (`usuario`),
  INDEX `fk_supervisor_usuario1_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_supervisor_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `BO_System`.`usuario` (`persona_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`back_office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`back_office` (
  `usuario_id` CHAR(36) NOT NULL,
  `supervisor` CHAR(36) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_back_office_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_back_office_supervisor1_idx` (`supervisor` ASC) VISIBLE,
  CONSTRAINT `fk_back_office_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `BO_System`.`usuario` (`persona_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_back_office_supervisor1`
    FOREIGN KEY (`supervisor`)
    REFERENCES `BO_System`.`supervisor` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`correo` (
  `sap` VARCHAR(25) NOT NULL,
  `referencia` TEXT(600) NULL,
  `telefono_contacto` VARCHAR(20) NOT NULL,
  `telefono_alternativo` VARCHAR(20) NULL,
  `destinatario` VARCHAR(100) NOT NULL,
  `persona_autorizada` VARCHAR(100) NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `estado_correo` VARCHAR(45) NOT NULL DEFAULT 'inicial',
  `fecha_entrega` DATETIME NULL,
  `codigo_postal` INT NOT NULL,
  `entrega_ok` VARCHAR(45) NULL DEFAULT 'inicial',
  `fecha_creacion` DATE NOT NULL,
  `fecha_limite` DATE NOT NULL,
  `numero_casa` INT NOT NULL,
  `estado_descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sap`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`cliente` (
  `persona_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`persona_id`),
  INDEX `fk_usuario_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona10`
    FOREIGN KEY (`persona_id`)
    REFERENCES `BO_System`.`persona` (`id_persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`vendedor` (
  `usuario` CHAR(36) NOT NULL,
  `supervisor` CHAR(36) NOT NULL,
  PRIMARY KEY (`usuario`),
  INDEX `fk_vendedor_usuario1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_vendedor_supervisor1_idx` (`supervisor` ASC) VISIBLE,
  CONSTRAINT `fk_vendedor_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `BO_System`.`usuario` (`persona_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vendedor_supervisor1`
    FOREIGN KEY (`supervisor`)
    REFERENCES `BO_System`.`supervisor` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`promocion` (
  `idpromocion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `porcentaje` DECIMAL(5,2) NOT NULL,
  `empresa_destinada` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `extra` TEXT(500) NULL,
  PRIMARY KEY (`idpromocion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`plan` (
  `idplan` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(6,2) NOT NULL,
  `gigabyte` INT NOT NULL,
  `llamadas` VARCHAR(45) NOT NULL,
  `mensajes` VARCHAR(45) NOT NULL,
  `beneficios` TEXT(600) NOT NULL,
  PRIMARY KEY (`idplan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `sds` VARCHAR(15) NOT NULL,
  `stl` VARCHAR(20) NOT NULL,
  `back_office` CHAR(36) NOT NULL,
  `sap` VARCHAR(25) NULL,
  `chip` ENUM('sim', 'esim') NOT NULL DEFAULT 'sim',
  `cliente` CHAR(36) NOT NULL,
  `vendedor` CHAR(36) NOT NULL,
  `promocion` INT NOT NULL,
  `plan` INT NOT NULL,
  `multiple` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idventa`),
  INDEX `fk_venta_back_office1_idx` (`back_office` ASC) VISIBLE,
  INDEX `fk_venta_correo1_idx` (`sap` ASC) VISIBLE,
  INDEX `fk_venta_cliente1_idx` (`cliente` ASC) VISIBLE,
  INDEX `fk_venta_vendedor1_idx` (`vendedor` ASC) VISIBLE,
  INDEX `fk_venta_promocion1_idx` (`promocion` ASC) VISIBLE,
  INDEX `fk_venta_plan1_idx` (`plan` ASC) VISIBLE,
  CONSTRAINT `fk_venta_back_office1`
    FOREIGN KEY (`back_office`)
    REFERENCES `BO_System`.`back_office` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_correo1`
    FOREIGN KEY (`sap`)
    REFERENCES `BO_System`.`correo` (`sap`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `BO_System`.`cliente` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_vendedor1`
    FOREIGN KEY (`vendedor`)
    REFERENCES `BO_System`.`vendedor` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_promocion1`
    FOREIGN KEY (`promocion`)
    REFERENCES `BO_System`.`promocion` (`idpromocion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_plan1`
    FOREIGN KEY (`plan`)
    REFERENCES `BO_System`.`plan` (`idplan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`linea_nueva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`linea_nueva` (
  `numero_gestor` INT NOT NULL,
  `multiple` INT NOT NULL DEFAULT 1,
  `venta` INT NOT NULL,
  PRIMARY KEY (`venta`),
  CONSTRAINT `fk_linea_nueva_venta1`
    FOREIGN KEY (`venta`)
    REFERENCES `BO_System`.`venta` (`idventa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`portabilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`portabilidad` (
  `spn` VARCHAR(20) NOT NULL,
  `empresa_origen` VARCHAR(45) NOT NULL,
  `mercado_origen` VARCHAR(45) NOT NULL,
  `numero_porta` VARCHAR(20) NOT NULL,
  `pin` INT NULL,
  `numero_gestor` VARCHAR(20) NULL,
  `venta` INT NOT NULL,
  PRIMARY KEY (`venta`),
  CONSTRAINT `fk_portabilidad_venta1`
    FOREIGN KEY (`venta`)
    REFERENCES `BO_System`.`venta` (`idventa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`reclamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`reclamo` (
  `fecha_creacion` DATE NOT NULL,
  `datos_adicionales` VARCHAR(50) NULL,
  `comentario` TEXT(600) NOT NULL,
  `sap` VARCHAR(25) NOT NULL,
  `id_reclamo` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_reclamo_correo1_idx` (`sap` ASC) VISIBLE,
  PRIMARY KEY (`id_reclamo`),
  CONSTRAINT `fk_reclamo_correo1`
    FOREIGN KEY (`sap`)
    REFERENCES `BO_System`.`correo` (`sap`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`comentario` (
  `estado` VARCHAR(45) NOT NULL,
  `contacto` VARCHAR(45) NOT NULL,
  `comentario` TEXT(600) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `usuario` CHAR(36) NOT NULL,
  `venta` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_table1_usuario1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_comentario_venta1_idx` (`venta` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_table1_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `BO_System`.`usuario` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_venta1`
    FOREIGN KEY (`venta`)
    REFERENCES `BO_System`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`estados` (
  `estado_actual` VARCHAR(45) NOT NULL DEFAULT 'INICIAL',
  `estado_descripcion` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_activacion` DATETIME NULL,
  `usuario_modificador` VARCHAR(45) NOT NULL,
  `id_estado` INT NOT NULL,
  `venta` INT NOT NULL,
  PRIMARY KEY (`id_estado`),
  INDEX `fk_estados_venta1_idx` (`venta` ASC) VISIBLE,
  CONSTRAINT `fk_estados_venta1`
    FOREIGN KEY (`venta`)
    REFERENCES `BO_System`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BO_System`.`alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BO_System`.`alerta` (
  `id_alerta` INT NOT NULL,
  `venta_idventa` INT NOT NULL,
  `alrta` VARCHAR(45) NOT NULL,
  `comentario` TEXT(600) NOT NULL,
  PRIMARY KEY (`id_alerta`),
  INDEX `fk_alerta_venta1_idx` (`venta_idventa` ASC) VISIBLE,
  CONSTRAINT `fk_alerta_venta1`
    FOREIGN KEY (`venta_idventa`)
    REFERENCES `BO_System`.`venta` (`idventa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
